name: Generate Dart Commits Badge

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  generate-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Commit Badge
        uses: ./.github/actions/create-badge
        with:
          repository: "dart-lang/sdk"
          author: "FMorschel"
          text: "Dart SDK Commits"
          logo: "dart"
          labelColor: "#0175C2"
          color: "lightgray"
          outputPath: "badges/dart-commits.svg"
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Commit and Push Badge
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add "badges/dart-commits.svg"
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Update commit dart badge"
          git push
